languageCode = "cz"
title = "Web od A do Z, České Budějovice, 2018"
theme = "ales-ruzicka"
baseURL = "https://czechitaswebcb2018.alesruzicka.eu"

[params]
  WebName = "Web od A do Z, České Budějovice, 2018"

[taxonomies]
  tag = "tags"